version: "3.7"
services:
  api:
    image: "marquezproject/marquez:${TAG}"
    container_name: marquez-api
    environment:
      - MARQUEZ_PORT=${API_PORT}
      - MARQUEZ_ADMIN_PORT=${API_ADMIN_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
      - "${API_ADMIN_PORT}:${API_ADMIN_PORT}"
    volumes:
      - data:/opt/marquez
    links:
      - "db:postgres"
    depends_on:
      - db
    entrypoint: ["/opt/marquez/wait-for-it.sh", "postgres:26257", "--", "./entrypoint.sh"]

  db:
    image: registry.gitlab.com/nexiot-ag/devops/persistence/granit/base-image:5.0.0
    container_name: marquez-db
    ports:
      - "26257:26257"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - MARQUEZ_DB=granit_local
      - MARQUEZ_USER=postgres
      - MARQUEZ_PASSWORD=postgres
    # Enables SQL statement logging (see: https://www.postgresql.org/docs/12/runtime-config-logging.html#GUC-LOG-STATEMENT)
    command: ["--accept-sql-without-tls"]

volumes:
  data:
  db-conf:
  db-init:
  db-backup:
